# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np


## Looping Through Arrays

In [17]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)


[[11 12 13]
 [14 15 16]]


In [18]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [19]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop works with entire rows of the array,
so multiplying by 2 affects all numbers in the row at once.

The second loop goes deeper into each row and works
with individual values one at a time.

In [20]:
for x in arrA:
    for y in x:
        loop_result = x * 2

        print(loop_result)


[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [25]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [26]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [23]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [24]:
stacked_array_ = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

ValueError: all input arrays must have the same shape

### This gives an error because both arrays must have the same shape to be stacked together.

In [27]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [28]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

### This fails because axis=1 means combining columns, but the arrays do not have matching row sizes.

In [29]:
h_result = np.hstack((arrA, arrA))
print(h_result)

# hstack joins arrays horizontally (side-by-side)

v_result = np.vstack((arrA, arrA))
print(v_result)

# vstack joins arrays vertically (top-to-bottom)

d_result = np.dstack((arrA, arrA))
print(d_result)

# dstack stacks arrays depth-wise (creates a 3D array)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [30]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This creates 2 arrays.
# Each resulting array is still 1-dimensional.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [31]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# This creates 3 arrays.
# Each resulting array is also 1-dimensional.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [32]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


In [33]:
## Sorting and Filtering Arrays

In [34]:
arrB = np.array([[7,6],
                 [13,5],
                 [7,3]])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [35]:
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [36]:
y = arrB >= 7
arrD = arrB[y]

print(arrD)

[ 7 13  7]
