# Exercise 1.B NumPy Random

## Generating Random Numbers


In [1]:
import numpy as np

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[ 7 18]


In [3]:
r_2 = np.random.randint(1, 20, size=(1,2))
print(r_2)

[[ 1 14]]


In [4]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.37198554]
 [0.65071807]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)

[[84 40 49 22 76]
 [64 82 40 98 54]
 [57 40 96 84 82]
 [21 91 98 55 20]]


In [6]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.01672951 0.52627211 0.07676931 0.37852487 0.6085188 ]
 [0.12258146 0.47867249 0.03006758 0.40762242 0.96550352]
 [0.71491295 0.79266755 0.58376428 0.99911341 0.81386289]
 [0.54267262 0.65054219 0.26208972 0.76939917 0.14504386]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Jack",
    "Sue",
    "Maddie",
    "Nick",
    "Theo",
    "Eric",
    "Hawa",
    "Gavin",
    "Zeke",
    "Maddy",
    "Karina",
    "Josh"
])

In [8]:
call_on = np.random.choice(students)
print(call_on)

Hawa


In [9]:
breakout_groups = np.random.choice(students, size=(3,4))
print(breakout_groups)

#Some students may appear multiple times, while others may not appear at all; so it is not the best way.

[['Zeke' 'Nick' 'Theo' 'Theo']
 ['Maddie' 'Jack' 'Maddie' 'Jack']
 ['Maddie' 'Gavin' 'Gavin' 'Maddy']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.10, 0.10, 0.10, 0.05,
       0.05, 0.05, 0.05, 0.05, 0.05, 0.00]
)

print(call_on_weighted)


# Student 1 has a 30% chance.
# Student 12 has a 0% chance.
# Other students were assigned smaller probabilities.

['Maddy' 'Jack' 'Eric' 'Eric' 'Sue']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[11.08374639  7.52896042  8.73189295 18.46046816 15.75239425]
 [ 4.69482929 11.36540926  5.37304302  6.81098051  9.18186552]
 [12.50041714 16.77159058 14.84273806  8.49695732 12.26802237]
 [ 2.87179025 10.33388156  9.73074563 10.24747363  2.28737663]]
