# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np


# Exercise 1.C Performing operations on arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)

r_2 = np.random.randint(1, 20, size=(1,2))

r_3 = np.random.rand(2,1)

r_4 = np.random.randint(20, 100, size=(4,5))

r_5 = np.random.rand(4,5)

## Permutations

In [3]:
print(r_4)

[[70 59 59 91 73]
 [82 45 83 42 78]
 [37 55 47 41 58]
 [95 53 74 68 34]]


In [4]:
np.random.shuffle(r_4)

print(r_4)

[[70 59 59 91 73]
 [95 53 74 68 34]
 [82 45 83 42 78]
 [37 55 47 41 58]]


Shuffle changes the order of rows inside the original array.
The original array itself is modified.

In [5]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)

print(r_4)

[[95 53 74 68 34]
 [37 55 47 41 58]
 [70 59 59 91 73]
 [82 45 83 42 78]]
[[70 59 59 91 73]
 [95 53 74 68 34]
 [82 45 83 42 78]
 [37 55 47 41 58]]


shuffle changes the original array directly,
while permutation creates a shuffled copy
without changing the original array.


## Mathematical Operations

In [7]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result = np.add(r_1, r_2)

print(result)
print(result.shape)


[14 19]
(2,)
[[10 12]]
(1, 2)
[[24 31]]
(1, 2)


In [8]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result = np.add(r_1, r_3)

print(result)
print(result.shape)

[14 19]
(2,)
[[0.37757744]
 [0.78413178]]
(2, 1)
[[14.37757744 19.37757744]
 [14.78413178 19.78413178]]
(2, 2)


In [9]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result = np.add(r_2, r_4)

print(result)
print(result.shape)

[[10 12]]
(1, 2)
[[70 59 59 91 73]
 [95 53 74 68 34]
 [82 45 83 42 78]
 [37 55 47 41 58]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [10]:
np.add(r_1, r_4)

# Error explanation:
# r_1 and r_4 cannot broadcast together because
# their shapes are incompatible.

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [12]:
print(np.add(np.array([1]), r_4))

[[71 60 60 92 74]
 [96 54 75 69 35]
 [83 46 84 43 79]
 [38 56 48 42 59]]


In [13]:
print(np.add(np.array([[1]]), r_4))

[[71 60 60 92 74]
 [96 54 75 69 35]
 [83 46 84 43 79]
 [38 56 48 42 59]]


In [14]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[71 60 60 92 74]
 [96 54 75 69 35]
 [83 46 84 43 79]
 [38 56 48 42 59]]


In [15]:
print(np.add(np.array([[1],[1]]), r_4))

# Error explanation:
# The shapes do not align properly for broadcasting.

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting allows NumPy to perform operations
on arrays with different shapes when the dimensions
are compatible.

Smaller arrays are stretched across larger arrays.
The resulting array usually takes the larger shape.

## Rounding

In [16]:
print(r_3)

[[0.37757744]
 [0.78413178]]


In [17]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [18]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [19]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [20]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [21]:
print(np.round(r_3, 2))

[[0.38]
 [0.78]]


## Cumulative Operations

In [22]:
print(r_4)

[[70 59 59 91 73]
 [95 53 74 68 34]
 [82 45 83 42 78]
 [37 55 47 41 58]]


In [23]:
print(np.sum(r_4))

1244


In [24]:
print(np.sum(r_4, axis=0))

[284 212 263 242 243]


In [25]:
print(np.sum(r_4, axis=1))

[352 324 330 238]


In [26]:
print(np.cumsum(r_4))

[  70  129  188  279  352  447  500  574  642  676  758  803  886  928
 1006 1043 1098 1145 1186 1244]


In [27]:
print(np.cumsum(r_4, axis=0))

[[ 70  59  59  91  73]
 [165 112 133 159 107]
 [247 157 216 201 185]
 [284 212 263 242 243]]


## Grocery Problem

In [28]:
# [vegetables, fruits, snacks, beverages]

bag1 = np.array([2,3,4,0])

bag2 = np.array([4,0,1,2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [29]:
print(
    f"The first bag contains {np.sum(bag1)} items, "
    f"and the second bag contains {np.sum(bag2)} items."
)

The first bag contains 9 items, and the second bag contains 7 items.


In [30]:
totals = bag1 + bag2

print(
    f"There are {totals[0]} vegetables, "
    f"{totals[1]} fruits, "
    f"{totals[2]} boxes of snacks, "
    f"and {totals[3]} beverages in the two grocery bags."
)

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [31]:
cagla = np.array([5,4,6,4,2])

print(cagla)

[5 4 6 4 2]
